export const items = [
  {
    id: 1,
    name: "Louboutins",
    blurb: "12 inches",
    rating: 4,
    image: "/Christian Louboutin.jpeg",
  },
  {
    id: 2,
    name: "Jimmy Choo",
    blurb: "6 inches",
    rating: 5,
    image: "/Jimmy Choo heels.jpeg",
  },
  {
    id: 3,
    name: "Tomford",
    blurb: "7 inches",
    rating: 4,
    image: "/Hermes.jpeg",
  },
  {
    id: 4,
    name: "Givinchy",
    blurb: "12 inches",
    rating: 5,
    image: "/Givinchy.jpeg",
  },
  {
    id: 5,
    name: "Mach&mach",
    blurb: "6 inches",
    rating: 5,
    image: "/Mach&mach.jpeg",
  },
  {
    id: 6,
    name: "Alexander Wang",
    blurb: "7 inches",
    rating: 4,
    image: "/Alexander.jpeg",
  },
  {
    id: 7,
    name: "Valentino",
    blurb: "12 inches",
    rating: 4.5,
    image: "/Valentino.jpeg",
  },
  {
    id: 8,
    name: "D&G",
    blurb: "6 inches",
    rating: 5,
    image: "/D&G.jpeg",
  },
  {
    id: 9,
    name: "Channel",
    blurb: "6 inches",
    rating: 5,
    image: "/Channel.jpeg",
  },
  {
    id: 10,
    name: "Dior",
    blurb: "7 inches",
    rating: 4,
    image: "/Dior.jpeg",
  },
  {
    id: 11,
    name: "Ego",
    blurb: "12 inches",
    rating: 5,
    image: "/Ego.jpeg",
  },
  {
    id: 12,
    name: "Castillo",
    blurb: "12 inches",
    rating: 5,
    image: "/Castillo.jpeg",
  },
];
